-- Human-owned root of the roadmap target signatures.
--
-- The per-topic `README.md` files are the definitive roadmaps. The Lean `Suggested.lean`
-- files suggest declaration forms for particular milestones (with `sorry`, which is
-- allowed here); they are not exhaustive, and discharging one does not finish its roadmap.
--
-- This file deliberately carries no imports, and a roadmap must not add one. `lakefile.toml`
-- globs every module under `EpsilonEridaniRoadmap/`, so `lake build` compiles each roadmap whether or
-- not it is named here, and catches an orphaned or broken target either way. The list this file
-- used to carry was appended to, so every concurrent roadmap pull request edited its last line
-- and conflicted with every other. It had also silently drifted three roadmaps out of date
-- without the `build` check noticing, which is what showed the list was not load-bearing.
